# Generated by Django 4.2.6 on 2023-11-22 07:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "Статья", "verbose_name_plural": "Статьи"},
        ),
        migrations.AlterModelOptions(
            name="blogcategories",
            options={
                "verbose_name": "Категорию блога",
                "verbose_name_plural": "Категории блога",
            },
        ),
    ]
