# Generated by Django 4.2.6 on 2023-11-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0003_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='baskets',
        ),
        migrations.AddField(
            model_name='customer',
            name='baskets',
            field=models.ManyToManyField(related_name='customers', to='baskets.baskets'),
        ),
    ]
