# Generated by Django 4.2.6 on 2023-11-11 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 11, 11, 10, 2, 58, 460704, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
