# Generated by Django 4.2.6 on 2023-11-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_size_remove_product_size_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('Size S', 'S'), ('Size M', 'M'), ('Size L', 'L'), ('Size XL', 'XL')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
