# Generated by Django 4.2.6 on 2023-11-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_size_alter_product_options_remove_product_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('Size S', 'S'), ('Size M', 'M'), ('Size L', 'L'), ('Size XL', 'XL')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
