# Generated by Django 4.2.6 on 2023-11-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_choices_remove_product_size_product_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
